### PR TITLE
Fix typo in next_prime

### PR DESCRIPTION
**Pull request by johnoliverdriscoll**
Resolves https://github.com/dignifiedquire/num-bigint/issues/44

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Can you clarify as to why this should be? cc @kongstedet

**Comment by kongstedet** [comment]
moduli should hold the residues, but the initialization uses the quotients

**Comment by darconeous** [comment]
I can confirm that this patch also fixes #50.

**Review by dignifiedquire — APPROVED** [review]
thanks for catching this

**Pull request merged**
