### PR TITLE
Fix min versions build

### PR DESCRIPTION
**Pull request by newpavlov**
It causes issues in the `rsa` crate, see https://github.com/RustCrypto/RSA/pull/135.

### CODE REVIEW

**Comment by tarcieri** [comment]
@dignifiedquire ping

**Comment by dignifiedquire** [comment]
closing in favor of https://github.com/dignifiedquire/num-bigint/pull/47

**Comment by dignifiedquire** [comment]
should be fixed in `0.8.2`

**Comment by tarcieri** [comment]
Thanks!

**Pull request closed without merging**
